# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1d62f16cb45a5a6c285cad1f9a34e343667dff2b838c5571bbc279816a7b72fbdc9fd7f69f5d42a5999e07d8b27a39b280cc790ea1854eed90adc974b34b6c4

test:
  secret_key_base: db4963d4b5d8bfdb49d4497ed7034dbf436211af1a7b6f938d905dfd563c7e94f0c77b6201469b02d7b504713bb27929a4a325b8d089abbc10f1af4ed3271a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
